### ISSUE TITLE
How much Flash/SRAM this port required to work?

### ISSUE THREAD

**Issue by ponyatov** [avr-uip/avr-uip#1]
I'm searching for extra minimalistic IP/UDP implementation for use in IoT devices (CoAP/UDP), and need some statistics what is extra minimal resources does IP stack require to be quite usable.

**Comment by matsievskiysv** [comment]
Try reading [this](https://github.com/avr-uip/avr-uip/blob/master/doc/uip-refman.pdf) documentation.
> It is possible to run the uIP implementation with as little as 200 bytes of RAM, but such a configuration will provide extremely low throughput and will only allow a small number of simultaneous connections.
